const products = [
  {
    _id: '1',
    name: 'xxxxxxx',
    image: '/images/1.jpg',
    description:
      'blabla',
    brand: 'xxxx',
    category: 'xxxxxx',
    price: 999,
    countInStock: 10,
    rating: 4.9,
    numReviews: 5,
  },
  {
    _id: '2',
    name: '2222222',
    image: '/images/2.jpg',
    description:
      'blabla',
    brand: 'xxxx',
    category: 'xxxxxx',
    price: 999,
    countInStock: 10,
    rating: 3,
    numReviews: 5,
  },
  {
    _id: '3',
    name: '3333333333333333333',
    image: '/images/3.jpg',
    description:
      'blabla',
    brand: 'xxxx',
    category: 'xxxxxx',
    price: 999,
    countInStock: 10,
    rating: 4.9,
    numReviews: 5,
  },
  {
    _id: '4',
    name: 'xxxxxxx',
    image: '/images/4.jpg',
    description:
      'blabla',
    brand: 'xxxx',
    category: 'xxxxxx',
    price: 999,
    countInStock: 10,
    rating: 4.9,
    numReviews: 5,
  },
  {
    _id: '5',
    name: 'xxxxxxx',
    image: '/images/5.jpg',
    description:
      'blabla',
    brand: 'xxxx',
    category: 'xxxxxx',
    price: 999,
    countInStock: 10,
    rating: 4.9,
    numReviews: 5,
  },
  {
    _id: '6',
    name: 'xxxxxxx',
    image: '/images/6.jpg',
    description:
      'blabblablablablablablablablablablala',
    brand: 'xxxx',
    category: 'xxxxxx',
    price: 999,
    countInStock: 10,
    rating: 4.9,
    numReviews: 5,
  },
  {
    _id: '7',
    name: 'xxxxxxx',
    image: '/images/7.jpg',
    description:
      'blabblablablablablablablablablablablablablablala',
    brand: 'xxxx',
    category: 'xxxxxx',
    price: 999,
    countInStock: 10,
    rating: 4.9,
    numReviews: 5,
  },
  {
    _id: '8',
    name: 'xxxxxxx',
    image: '/images/8.jpg',
    description:
      'blablablablablablablablablablablablablabla',
    brand: 'xxxx',
    category: 'xxxxxx',
    price: 999,
    countInStock: 10,
    rating: 4.9,
    numReviews: 5,
  },
  {
    _id: '9',
    name: 'xxxxxxx',
    image: '/images/9.jpg',
    description:
      'blablablablablablablablablablablablablablablabla',
    brand: 'xxxx',
    category: 'xxxxxx',
    price: 999,
    countInStock: 10,
    rating: 4.9,
    numReviews: 5,
  },
  {
    _id: '10',
    name: 'xxxxxxx',
    image: '/images/10.jpg',
    description:
      'blablablablablablablablablablablabla',
    brand: 'xxxx',
    category: 'xxxxxx',
    price: 999,
    countInStock: 10,
    rating: 4.9,
    numReviews: 5,
  },
]

export default products
